# Builds grafana-dashboard.yaml: a ConfigMap the Grafana sidecar loads as the "Demo App" dashboard.
import json

PROM = {"type": "prometheus", "uid": "prometheus"}
LOKI = {"type": "loki", "uid": "loki"}


def panel(id, title, x, y, w, h, targets, kind="timeseries", unit=None, ds=PROM, **extra):
    p = {"id": id, "title": title, "type": kind, "datasource": ds,
         "gridPos": {"x": x, "y": y, "w": w, "h": h},
         "targets": [dict(refId=chr(65 + i), datasource=ds, **t) for i, t in enumerate(targets)],
         "fieldConfig": {"defaults": {"unit": unit} if unit else {}, "overrides": []}}
    p.update(extra)
    return p


def q(expr, legend=""):
    return {"expr": expr, "legendFormat": legend}


panels = [
    {"id": 100, "type": "row", "title": "Application health", "collapsed": False, "gridPos": {"x": 0, "y": 0, "w": 24, "h": 1}},
    panel(1, "Scrape targets up", 0, 1, 6, 4, [q('sum by (service) (up{namespace="demo"})', "{{service}}")], "stat",
          options={"colorMode": "background", "graphMode": "none", "textMode": "value_and_name"},
          fieldConfig={"defaults": {"thresholds": {"mode": "absolute", "steps": [{"color": "red", "value": None}, {"color": "green", "value": 1}]}}, "overrides": []}),
    panel(2, "Ready pods", 6, 1, 6, 4, [q('sum by (deployment) (kube_deployment_status_replicas_ready{namespace="demo", deployment=~"frontend|backend"})', "{{deployment}}")], "stat",
          options={"colorMode": "background", "graphMode": "none", "textMode": "value_and_name"},
          fieldConfig={"defaults": {"thresholds": {"mode": "absolute", "steps": [{"color": "red", "value": None}, {"color": "green", "value": 1}]}}, "overrides": []}),
    panel(3, "Container restarts (1h)", 12, 1, 6, 4, [q('sum(increase(kube_pod_container_status_restarts_total{namespace="demo"}[1h]))', "restarts")], "stat",
          options={"colorMode": "background", "graphMode": "none"},
          fieldConfig={"defaults": {"decimals": 0, "thresholds": {"mode": "absolute", "steps": [{"color": "green", "value": None}, {"color": "orange", "value": 1}]}}, "overrides": []}),
    panel(4, "Firing alerts", 18, 1, 6, 4, [q('count(ALERTS{alertstate="firing", team="demo"}) or vector(0)', "firing")], "stat",
          options={"colorMode": "background", "graphMode": "none"},
          fieldConfig={"defaults": {"thresholds": {"mode": "absolute", "steps": [{"color": "green", "value": None}, {"color": "red", "value": 1}]}}, "overrides": []}),

    {"id": 101, "type": "row", "title": "Golden signals", "collapsed": False, "gridPos": {"x": 0, "y": 5, "w": 24, "h": 1}},
    panel(5, "Request rate", 0, 6, 8, 8, [q("podinfo:http_requests:rate1m", "{{service}}")], unit="reqps"),
    panel(6, "Error ratio (5xx)", 8, 6, 8, 8, [q("podinfo:http_errors:ratio1m", "{{service}}")], unit="percentunit"),
    panel(7, "Latency p50 / p95", 16, 6, 8, 8, [
        q('histogram_quantile(0.50, sum by (service, le) (rate(http_request_duration_seconds_bucket{namespace="demo"}[2m])))', "{{service}} p50"),
        q('histogram_quantile(0.95, sum by (service, le) (rate(http_request_duration_seconds_bucket{namespace="demo"}[2m])))', "{{service}} p95")], unit="s"),

    {"id": 102, "type": "row", "title": "Resources", "collapsed": False, "gridPos": {"x": 0, "y": 14, "w": 24, "h": 1}},
    panel(8, "Pod CPU (% of limit)", 0, 15, 8, 8, [q(
        'sum by (pod) (rate(container_cpu_usage_seconds_total{namespace="demo", container="podinfo"}[1m])) / sum by (pod) (kube_pod_container_resource_limits{namespace="demo", container="podinfo", resource="cpu"})', "{{pod}}")],
        unit="percentunit"),
    panel(9, "Pod memory (working set)", 8, 15, 8, 8, [q(
        'sum by (pod) (container_memory_working_set_bytes{namespace="demo", container="podinfo"})', "{{pod}}")], unit="bytes"),
    panel(10, "Node CPU / memory utilisation", 16, 15, 8, 8, [
        q('1 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m]))', "cpu {{instance}}"),
        q('1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes', "mem {{instance}}")], unit="percentunit"),

    {"id": 103, "type": "row", "title": "Logs (Loki)", "collapsed": False, "gridPos": {"x": 0, "y": 23, "w": 24, "h": 1}},
    panel(11, "frontend + backend logs", 0, 24, 24, 9, [{"expr": '{namespace="demo", app=~"frontend|backend"}'}], "logs", ds=LOKI,
          options={"showTime": True, "wrapLogMessage": False, "sortOrder": "Descending"}),
]

dash = {"uid": "demo-app", "title": "Demo App - Monitoring", "tags": ["session20"], "timezone": "browser",
        "schemaVersion": 39, "refresh": "10s", "time": {"from": "now-15m", "to": "now"}, "panels": panels}

cm = f"""# Generated by make_dashboard.py. The Grafana sidecar loads any ConfigMap labelled grafana_dashboard=1.
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-dashboard
  namespace: demo
  labels:
    grafana_dashboard: "1"
data:
  demo-app.json: |
"""
cm += "\n".join("    " + l for l in json.dumps(dash, indent=2).split("\n")) + "\n"
open("grafana-dashboard.yaml", "w").write(cm)
print("wrote grafana-dashboard.yaml")
