apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pvc
  namespace: session13
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
